const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export { FETCH_USER_ERROR, FETCH_USER_REQUEST, FETCH_USER_SUCCESS }