
export const ADDINGREDIENTS = 'ADD-INGREDIENTS';
export const REMOVEINGREDIENTS = 'REMOVE-INGREDIENTS';
export const PURCHASABLE = 'PURCHASABLE';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const ORDERS_FETCH_FAIL = 'ORDERS_FETCH_FAIL'
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS'
export const ORDERS_FETCH_INIT = 'ORDERS_FETCH_INIT'

